[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'michaeljsmith/vim-indent-object'
[[plugins]]
repo = 'cohama/lexima.vim'
[[plugins]]
repo = 'thaerkh/vim-workspace'
hook_add = '''
" let g:workspace_autocreate = 1
nnoremap <leader>s :ToggleWorkspace<CR>
'''
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
" let g:airline_theme = 'codedark'
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab
'''
depends = ['tpope/vim-fugitive']
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'tpope/vim-commentary'
[[plugins]]
repo = 'tomasiser/vim-code-dark'
[[plugins]]
repo = 'kuroitu/pyceberg'
[[plugins]]
repo = 'vim-python/python-syntax'
hook_add = '''
let g:python_highlight_all=1
let g:python_version_2=0
let b:python_version_2=0
'''
# [[plugins]]
# repo = 'Mofiqul/vscode.nvim'



# [[plugins]]
# repo =  'wbthomason/packer.nvim'
[[plugins]]
repo =  'neovim/nvim-lspconfig'
[[plugins]]
repo =  'williamboman/mason.nvim'
[[plugins]]
repo =  'williamboman/mason-lspconfig.nvim'
[[plugins]]
repo =  'hrsh7th/nvim-cmp'
[[plugins]]
repo =  'hrsh7th/cmp-nvim-lsp'
[[plugins]]
repo =  'hrsh7th/vim-vsnip'

